projects:
  contacts:
    schemaPath: amplify/backend/api/contacts/build/schema.graphql
    includes:
      - ui/src/generated/aws/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ui/src/generated/aws/API.ts
        docsFilePath: ui/src/generated/aws
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
